### ISSUE TITLE
AppsGettingStarted.md is inconsistent with GettingStarted.md 

### ISSUE THREAD

**Issue by mcharleb** [ATLFlight/ATLFlightDocs#20]
Both documents describe different ways of installing the qrlSDK.

**Comment by mcharleb** [comment]
@rkintada can you have a look at this and decide what method you want to use?

**Comment by skye-AL** [comment]
@bharath374 This is indeed confusing. I just tried to build the camera-deamon using the description under [](url) [ii. Camera Programming](https://github.com/ATLFlight/ATLFlightDocs/blob/master/CameraProg.md) and failed. This could be because I installed the qrlSDK using the cross_toolchain repository, or because it is anyway broken. Here is what I did: 
In XXX/camerad-sample/media/camera-daemon I typed:
 `make -f sdk_use.mk all`
and got the following error: 
```
legatus@legatus-ThinkPad-T440p:~/camerad-sample/media/camera-daemon$ make -f sdk_use.mk all
g++  -std=c++11 -DHAVE_SYS_UIO_H -I /usr/include/live555 -I /usr/include/omx -I /usr/include/linux-headers/usr/include -I src  -c -o src/camerad.o src/camerad.cpp
In file included from src/camerad.cpp:41:0:
src/camerad.h:33:20: fatal error: camera.h: No such file or directory
compilation terminated.
```
Then in camera-deamon/sdk_use.mk I replaced
`$(SDKTARGETSYSROOT)` with `$(HEXAGON_ARM_SYSROOT)`

As the file still wasn't found I added the line
`CPPFLAGS += -I $(HEXAGON_ARM_SYSROOT)/usr/include`

as on instance of the camera.h file was suited there. However, new errors showed up then:
```
legatus@legatus-ThinkPad-T440p:~/camerad-sample/media/camera-daemon$ make -f sdk_use.mk all
g++  -std=c++11 -DHAVE_SYS_UIO_H -I /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/live555 -I /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/omx -I /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/linux-headers/usr/include -I /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include -I src  -c -o src/camerad.o src/camerad.cpp
In file included from /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/netinet/in.h:22:0,
                 from src/camerad.cpp:37:
/home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/stdint.h:148:0: warning: "__INT64_C" redefined
 #  define __INT64_C(c) c ## LL
 ^
<built-in>: note: this is the location of the previous definition
In file included from /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/netinet/in.h:22:0,
                 from src/camerad.cpp:37:
/home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/stdint.h:149:0: warning: "__UINT64_C" redefined
 #  define __UINT64_C(c) c ## ULL
 ^
<built-in>: note: this is the location of the previous definition
In file included from /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/endian.h:60:0,
                 from /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/bits/waitstatus.h:64,
                 from /home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/stdlib.h:42,
                 from /usr/include/c++/5/cstdlib:72,
                 from src/camerad.cpp:30:
/home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/bits/byteswap.h:74:17: error: ‘__uint64_t’ does not name a type
 static __inline __uint64_t
                 ^
In file included from /usr/include/c++/5/cstdlib:72:0,
                 from src/camerad.cpp:30:
/home/legatus/Qualcomm/qrlinux_v4_sysroot/merged-rootfs/usr/include/stdlib.h:510:35: error: expected initializer before ‘__attribute_alloc_size__’
      __THROW __attribute_malloc__ __attribute_alloc_size__ ((2)) __wur;
```
.... I will now try to install the qrlsdk as described here [AppsGettingStarted.md](https://github.com/ATLFlight/ATLFlightDocs/blob/master/AppsGettingStarted.md) and see whether these error persist.

**Comment by skye-AL** [comment]
Reinstalling the qrlsdk as described here [AppsGettingStarted](https://github.com/ATLFlight/ATLFlightDocs/blob/master/AppsGettingStarted.md) and installing the 32 bit libraries
`sudo apt-get install zlib1g:i386`
and then following the instructions here [CameraProg.md](https://github.com/ATLFlight/ATLFlightDocs/blob/master/CameraProg.md) worked. I lack knowledge to support you here, but one single installation of the qrlSDK would be nicer (see also gcc-linaro-arm-linux-gnueabihf-4.8 vs 4.9).

**Comment by bharath374** [comment]
The installation instructions have now been cleaned up, and there is now only one documented procedure. Please see: https://github.com/ATLFlight/ATLFlightDocs
